version: '3'

services:
  elasticsearch:
    user: root
    image: 'bitnami/elasticsearch:7.17.18'
    ports:
      - 9200:9200
    volumes:
      - './docker/elasticsearch-data:/bitnami/elasticsearch'